// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package storagemock is a generated GoMock package.
package storagemock

import (
	reflect "reflect"
	time "time"
	model "url-shortener/model"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockStorage) Load(urlID string) (model.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", urlID)
	ret0, _ := ret[0].(model.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockStorageMockRecorder) Load(urlID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockStorage)(nil).Load), urlID)
}

// LoadClientIP mocks base method.
func (m *MockStorage) LoadClientIP(clientIP string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadClientIP", clientIP)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadClientIP indicates an expected call of LoadClientIP.
func (mr *MockStorageMockRecorder) LoadClientIP(clientIP interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadClientIP", reflect.TypeOf((*MockStorage)(nil).LoadClientIP), clientIP)
}

// Save mocks base method.
func (m *MockStorage) Save(urlID, url, expireAt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", urlID, url, expireAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStorageMockRecorder) Save(urlID, url, expireAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStorage)(nil).Save), urlID, url, expireAt)
}

// SaveClientIP mocks base method.
func (m *MockStorage) SaveClientIP(clientIP string, expireAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveClientIP", clientIP, expireAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveClientIP indicates an expected call of SaveClientIP.
func (mr *MockStorageMockRecorder) SaveClientIP(clientIP, expireAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveClientIP", reflect.TypeOf((*MockStorage)(nil).SaveClientIP), clientIP, expireAt)
}
